Release 0.20.0 (#34)

diff --git a/test/playground/mani.yaml b/test/playground/mani.yaml
--- a/test/playground/mani.yaml
+++ b/test/playground/mani.yaml
@@ -1,118 +1,151 @@
 import:
-  - ./tmp/projects.yaml
+  - ./imports/projects.yaml
+  - ./imports/tasks.yaml
+  - ./imports/targets.yaml
+  - ./imports/specs.yaml
+  - ./imports/themes.yaml
 
 projects:
-  example:
+  playground:
     path: .
 
-  tap-report:
-    path: frontend/tap-report
-    url: https://github.com/alajmo/tap-report
-    desc: A tap report theme
-    tags: [frontend]
-    env:
-      branch: lala
+  # kaka:
+  #   path: frontend/kaka
+  #   url: git+ssh://git@github.com/alajmo/dashgridk.git
+  #   tags: [frontend,node]
 
   dashgrid:
     path: frontend/dashgrid
     url: git+ssh://git@github.com/alajmo/dashgrid.git
-    # clone: git clone git@github.com:alajmo/dashgrid # default
-    desc: A highly customizable drag-and-drop grid
-    tags: [frontend, kaka]
-    env:
-      branch: hello
+    tags: [frontend,node]
+
+  tap-report:
+    path: frontend/tap-report
+    url: https://github.com/alajmo/tap-report
+    tags: [frontend]
 
   template-generator:
     url: git@github.com:alajmo/template-generator
-    desc: A simple bash script used to manage boilerplates
-    tags: [cli, bash]
+    tags: [cli,bash]
 
+# GLOBAL ENVS
 env:
-  DATE: $(date -u +"%Y-%m-%dT%H:%M:%S%Z")
-  VERSION: v5.1.0
+  VERSION: v0.1.0
   GIT: git --no-pager
+  DATE: $(date -u +"%Y-%m-%dT%H:%M:%S%Z")
+  # NO_COLOR: true
 
-themes:
-  default:
-    # table: ascii
-    tree: connected-bold
-
-  circle:
-    table: ascii
-    tree: circle
-
-specs:
-  default:
-    output: text
-    parallel: false
-    ignore_error: false
-
-  advanced:
-    output: table
-    parallel: false
-    ignore_error: true
-    omit_empty: true
-
-targets:
-  default:
-    all: true
-
-  advanced:
-    projects: [tap-report]
-    # all: true
-
-  all:
-    all: true
-
+# TASKS
 tasks:
   test:
-    spec: advanced
-    # target: all
-    cmd: echo $branch
+    desc: simple test task
+    # target: single-project
+    # spec:
+    #   parallel: true
+    #   output: table
+    # commands:
+    #   - task: damn
+    theme: advanced
+    cmd: echo "hello world"
+    # env:
+    #   NO_COLOR: true
+
+  git-status: git status
 
   echo:
     desc: Print hello world
-    # target:
-    #   paths: [frontend]
-    #   # projects: [pinto]
+    cmd: echo "hello world"
+    # spec: advanced
+    # spec: lala
+    # spec: lala
 
-    cmd: |
-      # sleep $(echo $RANDOM % 1 + 1 | bc; )
-      echo "hello world"
-      grep name package.json
-      # grep --color=auto name package.json
-      if [ -t 1 ] ; then echo \"terminal\"; else echo \"not a terminal\"; fi
+  ping:
+    desc: ping server
+    cmd: echo pong
 
   sleep:
-    theme: default
-    # target:
-    #   paths: [frontend]
-    cmd: |
-      sleep 5
-      pwd
+    desc: Sleep 5 seconds
+    cmd: sleep 5
+
+  status:
+    desc: git status
+    target: single-project
+    spec:
+      output: text
+    commands:
+      - mcd: git status
+      - cmd: git branch
+    cmd: echo done
+
+  text:
+    desc: test text info
+    env:
+      BRANCH: lala
+      FOO: bar
+    target: single-project
+    spec:
+      output: text
+    commands:
+      - task: echo
+      - cmd: echo lala
+      # - task: troll
+    cmd: echo hi
+
+  table:
+    env:
+      BRANCH: lala
+      FOO: bar
+    target: single-project
+    spec:
+      output: table
+    commands:
+      - task: echo
+      - cmd: echo lala
+    cmd: echo hi
 
   install:
     desc: npm install
     cmd: npm install
 
-  spec:
-    desc: testing spec
-    # spec: advanced
-    cmd: echo spec
-
   fail:
-    cmd: exit 1
-
-  beta:
+    desc: fail on purpose
+    cmd: |
+      echo "FAILED"
+      exit 1
+  node:
     target: all
     shell: node
-    cmd: console.log(123)
+    cmd: console.log("Running node.js example")
 
-  refs:
-    desc: Run multiple commands
-    spec: advanced
+  random-data:
+    desc: generate random data
+    cmd: |
+      jot -r 1
+      echo "RANDOM-DATA"
+      jot -r 2
+      sleep 2
+      jot -r 2
+      sleep 2
+
+  many:
+    desc: run many tasks
+    env:
+      BRANCH: lala
+      HELLO: WORLD
     target: all
-    shell: node
+    spec:
+      ignore_error: true
+    # theme: advanced
+
+    # theme:
+    #   text:
+    #     prefix: false
 
     commands:
-      - task: beta
+      - task: node
+      - task: fail
+      - task: echo
+      - task: random-data
+      - task: ping
+
+    cmd: echo "DONE"
