wip

diff --git a/test/playground/mani.yaml b/test/playground/mani.yaml
--- a/test/playground/mani.yaml
+++ b/test/playground/mani.yaml
@@ -1,6 +1,8 @@
+# IMPORTS
 import:
   - ./tmp/projects.yaml
 
+# PROJECTS
 projects:
   example:
     path: .
@@ -11,9 +13,7 @@ projects:
     desc: A tap report theme
     tags: ["frontend", "software"]
     env:
-      BRANCH: lala
-      FOO: bar
-      DATE: $(date)
+      BRANCH: main
 
   dashgrid:
     path: frontend/dashgrid
@@ -22,31 +22,170 @@ projects:
     desc: A highly customizable drag-and-drop grid
     tags: [frontend, kaka]
     env:
-      branch: hello
+      FOO: bar
 
   template-generator:
     url: git@github.com:alajmo/template-generator
     desc: A simple bash script used to manage boilerplates
     tags: [cli, bash]
 
+# GLOBAL ENVS
 env:
-  DATE: $(date -u +"%Y-%m-%dT%H:%M:%S%Z")
-  VERSION: v5.1.0
+  VERSION: v0.1.0
   GIT: git --no-pager
+  DATE: $(date -u +"%Y-%m-%dT%H:%M:%S%Z")
+
+# TASKS
+tasks:
+  test:
+    desc: simple test task
+    target: single-project
+    spec:
+      omit_empty: lala
+      parallel: hej
+    # commands:
+    #   - task: damn
+    cmd: echo "hello world"
+
+  git-status: git status
+
+  echo:
+    desc: Print hello world
+    cmd: echo "hello world"
+    spec: advanced
+    spec: lala
+    # spec: lala
+
+  ping:
+    desc: ping server
+    cmd: echo pong
+
+  sleep:
+    desc: Sleep 5 seconds
+    cmd: sleep 5
+
+  status:
+    desc: git status
+    target: single-project
+    spec:
+      output: text
+    commands:
+      - mcd: git status
+      - cmd: git branch
+    cmd: echo done
+
+  text:
+    desc: test text info
+    env:
+      BRANCH: lala
+      FOO: bar
+    target: single-project
+    spec:
+      output: text
+    commands:
+      - task: echo
+      - cmd: echo lala
+      # - task: troll
+    cmd: echo hi
+
+  table:
+    env:
+      BRANCH: lala
+      FOO: bar
+    target: single-project
+    spec:
+      output: table
+    commands:
+      - task: echo
+      - cmd: echo lala
+    cmd: echo hi
+
+  install:
+    desc: npm install
+    cmd: npm install
+
+  fail:
+    desc: fail on purpose
+    cmd: |
+      echo "FAILED"
+      exit 1
+
+  node:
+    target: all
+    shell: node
+    cmd: console.log("Running node.js example")
+
+  random-data:
+    desc: generate random data
+    cmd: |
+      jot -r 1
+      echo "RANDOM-DATA"
+      jot -r 2
+      sleep 2
+      jot -r 2
+      sleep 2
+
+  many:
+    desc: run many tasks
+    env:
+      BRANCH: lala
+      HELLO: WORLD
+    target: all
+    spec: advanced
+
+    commands:
+      - task: node
+      - task: echo
+      - task: random-data
+      - task: ping
+
+    cmd: echo "DONE"
+
+# SPECS
+specs:
+  default:
+    output: table
+    parallel: false
+    ignore_error: false
+    # omit_empty: kaka
+
+  hi:
+    parallel: kaka
+
+  advanced:
+    output: table
+    parallel: false
+    ignore_error: true
+    omit_empty: false
+
+# TARGETS
+targets:
+  default:
+    all: true
+    cwd: true
+
+  single-project:
+    projects: [tap-report]
+
+  all:
+    all: true
+
+# THEMES
 
 themes:
-  circle:
-    tree: circle
-
   default:
-    prefix: false
-
-    tree: connected-bold
+    tree:
+      style: connected-light
 
     text:
       prefix: true
+      header: true
+      header_char: "-"
+      # colors: ["blue", "red"]
 
     table:
+      style: ascii
+
       format:
         header: title
         row: default
@@ -70,7 +209,7 @@ themes:
             fg: green
             bg: black
             align: right
-            attr: underline
+            attr: normal
 
           desc:
             fg: red
@@ -81,7 +220,7 @@ themes:
           task:
             fg: blue
             # bg: black
-            align: center
+            align: left
             attr: bold
 
           rel_path:
@@ -105,13 +244,12 @@ themes:
           output:
             fg: hi_red
             # bg: black
-            align: right
+            align: left
             attr: normal
-
 
         row:
           project:
-            fg: hi_green
+            fg: hi_red
             bg: black
             align: left
             attr: normal
@@ -119,7 +257,7 @@ themes:
           tag:
             fg: magenta
             bg: black
-            align: right
+            align: left
             attr: normal
 
           desc:
@@ -136,209 +274,41 @@ themes:
 
           rel_path:
             fg: green
-            # bg: black
+            bg: black
             align: right
             attr: normal
 
           path:
             fg: green
-            # bg: black
+            bg: black
             align: right
             attr: normal
 
           url:
             fg: green
-            # bg: black
+            bg: black
             align: right
             attr: normal
 
           output:
             fg: hi_yellow
-            # bg: black
-            align: right
+            bg: black
+            align: left
             attr: normal
 
+        border:
+          header:
+            fg: yellow
+            bg: black
 
-        # border:
-        #   header:
-        #     fg: yellow
-        #     bg: black
+          row:
+            fg: yellow
+            bg: black
 
-        #   row:
-        #     fg: yellow
-        #     bg: black
+          row_alt:
+            fg: yellow
+            bg: black
 
-        #   row_alt:
-        #     fg: yellow
-        #     bg: black
-
-        #   footer:
-        #     fg: yellow
-        #     bg: black
-
-specs:
-  default:
-    output: text
-    parallel: false
-    ignore_error: false
-
-  advanced:
-    output: table
-    parallel: false
-    ignore_error: true
-    omit_empty: false
-
-targets:
-  default:
-    all: true
-
-  single:
-    projects: [tap-report]
-
-  advanced:
-    all: true
-    cwd: true
-    projects: [tap-report]
-    tags: [frontend,software]
-    paths: [frontend,frontend]
-
-  all:
-    all: true
-
-tasks:
-  test:
-    desc: simple test task
-    env:
-      # BRANCH: lala
-      FOO: bar
-      DATE: $(date)
-
-    target: single
-
-    spec:
-      output: text
-      # omit_empty: true
-
-    # commands:
-    #   - task: random-data-1
-    #   - task: echo
-    #   - task: random-data
-    #   - task: ping
-
-    cmd: echo "$BRANCH"
-    # cmd: echo "Hello World!"
-
-  random-data-1:
-    desc: generate random data
-    cmd: |
-      echo "RANDOM-DATA-1"
-      jot -r 2
-      sleep 2
-      jot -r 10
-      sleep 2
-
-  random-data:
-    desc: generate random data
-    cmd: |
-      # jot -r 1
-      echo "RANDOM-DATA"
-
-      jot -r 2
-      sleep 2
-      jot -r 2
-      sleep 2
-
-  text:
-    desc: test text info
-    env:
-      BRANCH: lala
-      FOO: bar
-      DATE: $(date)
-    target: single
-    spec:
-      output: text
-    commands:
-      - task: echo
-      - cmd: echo lala
-    cmd: echo hi
-
-  status:
-    desc: git status
-    target: single
-    spec:
-      output: text
-    commands:
-      - mcd: git status
-      - cmd: git branch
-
-    cmd: echo done
-
-  table:
-    env:
-      BRANCH: lala
-      FOO: bar
-      DATE: $(date)
-    target: single
-    spec:
-      output: table
-    commands:
-      - task: echo
-      - cmd: echo lala
-    cmd: echo hi
-
-  echo:
-    desc: Print hello world
-    cmd: echo "hello world"
-
-  ping:
-    desc: ping server
-    cmd: echo pong
-
-  # echo:
-  #   desc: Print hello world
-  #   # target:
-  #   #   paths: [frontend]
-  #   #   # projects: [pinto]
-
-  #   cmd: |
-  #     # sleep $(echo $RANDOM % 1 + 1 | bc; )
-  #     echo "hello world"
-  #     grep name package.json
-  #     # grep --color=auto name package.json
-  #     if [ -t 1 ] ; then echo \"terminal\"; else echo \"not a terminal\"; fi
-
-  sleep:
-    theme: default
-    # target:
-    #   paths: [frontend]
-    cmd: |
-      sleep 5
-      pwd
-
-  install:
-    desc: npm install
-    cmd: npm install
-
-  spec:
-    desc: testing spec
-    # spec: advanced
-    cmd: echo spec
-
-  fail:
-    cmd: exit 1
-
-  beta:
-    target: all
-    shell: node
-    cmd: console.log(123)
-
-  refs:
-    desc: Run multiple commands
-    spec: advanced
-    target: all
-    shell: node
-
-    commands:
-      - task: beta
-      - task: test
-      - task: test
+          footer:
+            fg: yellow
+            bg: black
